Feature/selected-products-in-card
Roman9131/online-shop pull request #4
Opened 2019-07-15 19:59 UTC by Roman9131

2019-07-16 08:23 UTC, ghost requested changes

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/index.tsx
> +  onDeleteFromCartClick: () => void;
эта функция как поймет какой item удалить? очевидно ты проебал id в параметрах ф-ии

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/index.tsx
> +  onIncrementProductClick: () => void;
а тут как узнать какой item гикрементить?

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/index.tsx
> +  onDecrementProductClick: () => void;
такая же хня) ты когда пишешь type ф-ии надо понимать че она делает и че принимает а потом уже описывать)

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/styles.sass
> +  border-style: solid
а в 1 строку слабо?))

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/styles.sass
> +  padding-right: 5px
порядок свойст пошел по пизде

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/styles.sass
> +  display: block
а div разве по дефолту не block?

2019-07-16 08:23 UTC, anatoliy8493 commented on src/components/CartSelectedItem/styles.sass
> +  box-sizing: border-box
на * ебани один раз и не страдай

2019-07-17 20:28 UTC, Roman9131 commented on src/components/CartSelectedItem/index.tsx
> +  onDeleteFromCartClick: () => void;
не тут не Id a MouseEvent,  добавлю описание

2019-07-17 20:31 UTC, Roman9131 commented on src/components/CartSelectedItem/index.tsx
> +  onIncrementProductClick: () => void;
не тут не Id a MouseEvent,  здесь только отслеживание самого клика, id крепится в Container - Cart  и получается на выходе функция 
private deleteProductFromCart = (id: string) => () => {
    const { deleteProductFromCart } = this.props;
    deleteProductFromCart(id);
  };

2019-07-17 20:31 UTC, Roman9131 commented on src/components/CartSelectedItem/index.tsx
> +  onDecrementProductClick: () => void;
тоже самое

2019-07-22 09:08 UTC, ghost approved these changes

2019-07-25 18:50 UTC, merged